CREATE DATABASE BANCORH;

-- TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO(
);


-- TABELA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO(
	id SERIAL,
	NOME VARCHAR (120),
	CONSTRAINT pk_departamento PRIMARY KEY (id)
);